data_dir: data/raw
processed_dir: data/processed
output_dir: output/charts

rm_sensors:
  "13.0": [31, 32]
  "15.0": [28, 29, 30]
  "17.0": [25, 26, 27]
  "21.5": [23, 24]
  "23.0": [21, 22]
  "33.6": [17, 18, 19, 20]
  "42.1": [13, 14, 15, 16]
  "46.0": [9, 10, 11, 12]
  "50.5": [7, 8]
  "51.9": [5, 6]
  "53.0": [3, 4]
  "54.0": [1, 2]

chart:
  figsize: [12, 6]
  dpi: 300
  hydrograph_color: blue
  sensor_color: orange
