action_id: trunk-upgrade-available
date: 2024-09-26 17:11:06
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1727370666
full_timestamp:
  nanos: 1227000
  seconds: 1727370666
trunk_version: 1.22.5
