# Project Configuration
project:
  name: "Hydrograph vs Seatek Sensors"
  version: "0.1.0"

# Data Processing Settings
data:
  input_path: "data/raw"
  output_path: "data/processed"

# Visualization Settings
visualization:
  output_dir: "output/charts"
  dpi: 300
  figure_size: [12, 8]

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/hydrosensors.log"