name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      # Add explicit permissions for security
      contents: read
      security-events: write
    
    steps:
      - uses: actions/checkout@v4  # Consider upgrading to v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_736140003 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
